= My first week
:published_at: 2014-10-25

I expected to write a post much earlier than this but the first week was so busy all I wanted to do in the evenings was get home and relax, screw the computer.

Monday was my first day and it was fun. I got thrown in at the deep end helping to form the squad I'm going to be a member of. Since I'd only been at the company 2.5hrs there was a lot to take in and do all of the sudden. The great thing about it though is that I helped form the team I'm going to be on and that I've been with it from the beginning. By the end of the week I was making my first code contributions to the Puppet code base.

Of course there was also some official business needing to take place like register with the necessary authorities and start my search for a home of my own.

Today was my first day off which was spent relaxing, looking at houses, getting a tour through Stockholm and eventually dinner and hanging out at a bar. It was great.

Even though it was a pretty grey and rainy day this city is just beautiful. Walking over the bridges and looking out over the lake, especially at night when the lights turn on, is breathtaking. I can only imagine how nice that same walk will be during spring and summer. The city seems to embrace you, like everything and everyone belongs somehow.

Whenever I'm in a new city I feel a bit uneasy at first, especially out at night on the streets because you don't know what you'll run into. I have a knack for walking into those exact parts of any town you should not be in alone at night, as a tourist. I'm sure this city has its spots but so far I haven't found them, even though I've gotten lost plenty of times. As I was walking home tonight from the bar it struck me how safe the streets feel, even those little alleys you know to normally avoid.

It was a great first week and I'm curious to see what the second week has in store for me. But, first things first, I'm going to enjoy my Sunday.