= Why I care about Pride

:hp-tags: gay, lgbtq, pride

If you're following me through social media it won't have escaped your attention that my avatar turned rainbow and there was a distinct increase in rainbows throughout my feed as we were ramping up to Pride.

Many people outside the LGBTQ community and even quite a few within don't realise the importance of Pride and just see it as a shameless parade. It is far from that.

After having helped organise our participation at Pride this year a few colleagues and I wrote a piece on the intranet about why we participated and what we did. I'm going to reproduce part of it here because I feel it explains the importance of Pride, to me personally too, very well.

[quote]
____
The parade is both a commemoration of the Stonewall Riots and a celebration of how far we’ve come since. Raids on gay establishments in the US were a common thing in the 1950’s and 1960’s but when police raided the Stonewall Inn in 1969 they lost control of the situation and a series of violent demonstrations followed. The first Pride march took place in June 1970, the year after the Stonewall riots.

It is all too easy to take for granted the liberties and freedoms that we have now. With a few exceptions it’s only in the last half century that same-sex sexual activity began to be decriminalised around the world, with over a third of countries still maintaining extremely harsh laws even now. Only in 1991 did the World Health Organization declassify it as a mental illness, and laws around equal treatment in employment, marriage, and even being able to talk about LGBTQ people in anything other than negative terms are very recent developments in what would be regarded as liberal democratic countries.

Despite the legal and social progress being made for gay, lesbian and bi people, transgender equality lags behind in legislation and social acceptance with sterilisation remaining as a requirement for gender recognition in most countries.

Being respected, accepted for who you are, equal in the eyes of the law and free from persecution is something worth celebrating where we have it. It also serves to highlight the fact that there are still countries where this is not the case, and there is still progress to be made at home.
____

This is what Pride is about and the reason I'll be giving it my 100% again next year.