= Saying "they"

:hp-tags: lgbtq

Based on a remark of a friend about preconceptions we have with regard to gender I started looking more carefully at how I use gender prononus. Though I'm usually fairly dilligent in writing I noticed I failed entirely in speech.

This usually happens to me when I meet a new person because at that point I have no context to go on. My autopilot takes over and based on their physique, dress style and preconceptions around gender that have been drilled into me for over 20 years, I end up selecting a pronoun like "he" or "she".

Without having made clear what one prefers as their gender pronoun I should not defer to some badly deduced context based on old preconceptions about someone's identity. Though there's a chance I'll get it right it can lead to situations where people feel very uncomfortable and even unwelcome based on such an assumption.

Some people have, insultingly, used the word 'it' instead, often to refer to transgender people. This is just plain wrong. People are people. Using 'it' is dehumanizing, insulting and completely unnecessary. The https://en.wikipedia.org/wiki/Singular_they[singular they] has been in use for centuries and is seeing more and more use today because it enables us to communicate in a gender-neutral and more inclusive way about people.

As such I've taken to force myself to use "they" when speaking about people, even if I know their (current) preferred gender pronoun. Hopefully the next time we meet I won't make that mistake again. If you notice me doing otherwise please forgive and correct me