= The Greek crisis

There's been a million posts about the current Greek debt crisis and there will be a million more. People will sling mud at each other for months to come. It won't be until years after that we will understand the full chain of events and look at it objectively. It will be an encyclopedia of its own and one of the darkest pages in the EU's history. If there even is an EU by then.

I grew up in Brussels, with one of my parents working for the European Commission. As a consequence I received my education at the European Schools, specifically Brussels II, in one of my native tongues, Dutch. Many other kids were at that school, each being educated in their own language; Italian, French, English, Portugeuse, Finish, Swedish, German and more.

As school progressed we had more and more communal classes, no longer separated in language sections. Classes like history and geography, informatics or gym and even math, physics, biology or chemisty were taught in a mxied group. In the last years, because there sometimes weren't enough pupils of a single section interested in an elective they were merged into other groups, usually French or English. For me this meant my two years of math advanced were taught in English. Others took on biology or chemistry in a language that was not their native tongue. The teaching of the secondary and tertiary languages always happened in a mixed group.

Though there are many things I could fault the European Schools for they gave me one thing I will always treasure, an understanding of and exposure to other countries and cultures. When we looked at history our focus was not so much on each individual nation but more how Europe was shaped as a whole and how all those disparate nations eventually came together. It was always about us, not about me versus them.

The founding principles of the EU are something I believe in, something that is profoundly beautiful to me (call it indoctrination if you must), something to aspire to. But if I look at the EU now, we have never looked so ugly before. Who started it and who said what doesn't matter. We have all taken part, and are all to blame, for the travesty that has occurred. So many of our core values have all been flung out the window, replaced by an us vs. them rhetoric from all parties involved.

Just look at some of the founding principles and guidelines as stated by the official site of the http://europa.eu/scadplus/constitution/objectives_en.htm[European Union]. Most of them have gone out the window. "The promotion of economic, social and territorial cohesion, and solidarity among Member States." When, I ask you? "Solidarity and mutual respect among peoples". Clearly we've failed that one. "Eradication of poverty". Turning Greece into a third world country certainly qualifies. I could go on and on.

The motto of the EU is "United in diversity". Looking at current events I don't see it. If this is what we call unity, to hell with all of it. The fact that any of the parties involved dares to still call themselves Europeans or acting in the best interest of the Union is laughable.

The only one in all of this that deserves an apology is Robert Schuman, for us having failed so miserably at what he so vailiantly set out to accomplish.