= Eurovision 2015
:hp-tags: eurovision, lgbtq

Last night http://en.wikipedia.org/wiki/Eurovision_Song_Contest[Europe went to war]. No the Germans didn't start it, we were just having a huge music contest followed by some political voting to decide who should win.

I adore the http://www.eurovision.tv/page/timeline[Eurovision Song Contest]. It might not be a manly thing to admit to but it's one of those things that just gets me ridiculously, over the rainbow to the moon, happy. It's also been a fairly progressive contest with LGBTQ members participating and people in drag aren't unfamiliar to the Eurovision either.

This year Austria hosted it in their beautiful capital of Vienna after the most fabulous bearded lady in history, http://conchitawurst.com[Conchita Wurst], took home the trophy. In a 206 point victory her http://youtu.be/QRUIava4WRM[Rise like a phoenix], which ought to be the theme to the next Bond movie, is one of the most popular acts in Eurovision history.

I'm pretty sure https://www.youtube.com/watch?v=9OxVSeAgIw0[I cried] last year, together with the rest of the LGBTQ community and our friends. Even more so after the crap one of the contestants, looking at you Mother Russia, has been pulling with their anti-gay propaganda laws setting back LGBTQ rights in Russia to almost the pre-WWII era. They even tried to get Conchita barred from participating and threatned to pull out if she would. No tears would've been shed if they had.

Yesterday https://www.youtube.com/watch?v=o_JH9DO1wn0[Conchita returned], gorgeous as ever, rocking those heels like many a woman wishes she could, with a waistline Marie-Antoinette would be jealous of.

The most remarkable thing of this year though was the battle going on between Russia and Sweden. The Russian entry was genuinly good and one of the better acts this year which got a lot of us nervous. As much as we want to support the artist we can't suppor the country. What would a Eurovision hosted in Russia even look like?

To be frank, Eurovision is one of the gayest events in Europe, safe for the Pride parades and you just can't be gay in Russia right now. Even worse, as the country hosting it, how much control would they get over the ESF preventing certain candidates from participating based on their gender or sexual identity? And if they would try to pull one over, what would the ESF do? I'm not sure any of us is ready to face that question just yet.

Thankfully once most of Eastern Europe was done cozying up to Russia, Sweden quickly closed the gap and took the lead. Though most Western European countries gave Russia some points, it really was a good act, Sweden eventually got enough of a lead that before everyone was done voting they, we, won.

Next year the Eurovision is coming to Sweden once more, the home of ABBA and the http://www.svenskafreds.se/singingsailor/[Singing Sailor defence system]. I'll be right there in the crowd with so many others.

