= LGBTQ in tech
:hp-tags: gay, lgbtq, tech, technology

Most people who know me know I'm gay, or that I identify as gay or queer or whichever way you're more comfortable phrasing or thinking about it. To put it bluntly: I like men, I date men, I sleep with men, I happen to be a man and it's all good.

The thing that struck me about tech when I started getting more involved in online communities is that no one cared about this fact. Well almost no one, there's always going to be a hate monger or two, even online. But I never got judged or excluded in tech because of my being gay. Even when other members of the community were aware of it, I got judged on my skills, on my contributions and insight, never based on which gender I preferred to take to bed.

I have to be honest about something though, I never really "came out" in tech as gay. I never really felt a need to state this. It came up every now and then during conferences and other meetups but I was never "that gay community member" and I never really wanted to be. I always told myself that that was because if I would be totally honest and upfront about it some people would judge me based on that fact alone, and I didn't want that.

You go through enough pain and terror as a kid growing up, realising you're different, coming out and what happens next. The fear that your friends, your family, might not accept you for who you are. The terrifying realisation that that bond you think you share might hinge on you "fitting in". That thought that your job security relies on your employer never finding out what you do in your off hours. I've been in plenty bad spots in my life but I don't think I've ever been as terrified as the first time I uttered the words "I need to tell you something... I'm gay".

Part of this is why I never really made myself "known" as gay in the tech community. Shame is a strong word, but I just didn't want to have to deal, not again. That was a mistake. I've grown since then. I'm a stronger person than that 17 year old kid ever was and if being "out and proud" in tech will help promote a discussion around that topic and will help others who might be trying to find their way in the tech community, then I want to be part of that effort.

The tech community has a bad name at times. We're the evil tech overlords, out to destroy the world, the bastards that want to get rich on the back of everyone else. Those people that everyone else in San Francisco regards with distrust, disgust, sometimes even hate. The root of everything evil, capitalism and the social and wealth divide of our current world. There's your fair amount of drama in different tech communities too, even over things as simple as changing documentation to use gender-neutral terms or codifying things like how we deal with each other as humans in our codes of conduct. But we're growing and growing up too.

My experience with the tech community has always been very positive but I realise not everyone else's has. It shows in that there is the https://twitter.com/hashtag/diversityintech[#DiversityInTech] hashtag, it shows in that we need to https://puppetlabs.com/blog/womenintech-jessica-devita-microsoft[talk about this], it shows in that efforts like http://transtechsocial.org[TransTech] exist. But we do have those efforts, we do talk. It's not always pretty but we're working on it, we're trying to get better at it. It's time I help out and I hope you will too.

I don't know exactly how to go about this but I can start small, identify myself as LGBTQ at those community events. I have a http://www.amazon.com/DISNEY-EXCLUSIVE-Mickey-Rainbow-Trading/dp/B0098QU6WY[Rainbow Mickey pin] which I'll make sure to have on my jacket when I'm at tech events just like I'll make a point in wearing an LGBTQ themed shirt. I hope that this way and together with the organisers of each event we'll be able to create a forum where we can discuss LGBTQ in tech and where people feel like that they can be a techie and LGBTQ too. But even if they don't feel comfortable just yet, know that they're not alone and that there are people that they can reach out and talk to about this.