= PyCon Sweden 2015
:hp-tags: pycon, pyconse, python

This year the second installement of PyCon Sweden took place right here in Stockholm. Being someone who tries to automate the world with the help of as much Python as inhumanly possible I attended, together with quite a few colleagues.

== Volunteers
Running a conference is hard, running a conference and not even getting paid for you efforts is harder. You need to draw all the satisfaction out of running this conference so it wouldn't be hard to understand that at some point it might just get a bit too much.

Nothing of the sort was apparent at PyCon Sweden, the volunteers were all excellent. Extremely friendly, helpful and exhibited exemplary behaviour. It was a great event and a lot of how smooth it all went was thanks to them.

== Oh the science
What struck me, and a lot of other people, was that there was a big focus on data science during the conference. If your talk wasn't about data science you were the odd one out, unless you were doing some web dev with Flask. This made me feel a bit weird with my "Puppet and Python" talk. Thankfully we had a Docker hippie or two too so I wasn't the only ops-y talk around.

The cool thing is, this data sience thing turns out to be quite a lot of fun. People had some very interesting talks with easy to follow examples, all neatly tied together in IPython notebooks.

It got me thinking about what I could actually do with all the data that I have and collect about our infrastructure. Right now it's super boring, a bit of inventory, some really vague "trending" and threshold based alerting but this opened my mind to a lot of other possibilities. There's certainly an interesting bridge we can build there that's worth investing some time in.

== Python all the things
I've never really been to Python events before, let alone a PyCon. What struck me, and I probably should've known, is that people have managed to use Python for everything. At this point I'm pretty convinced someone somewhere on this planet slices and toasts their bread with the help of Python.

When your life revolves around ops and automation it's really easy to lose sight of the fact that this language you're building your toolchain in can do so much more, and is used by so many to do other, crazy, thigns.

We had talks from the data science world, ops, web dev, embedded (ya people run Python there too, even Python 3.4), how to use Python to write a FUSE filesystem and so much more. Kenneth Reitz topped it all of with requests and his "Python for Humans" talk.

== Diversity
I have to touch on this topic as its a hot potato when it comes to tech events. PyCon Sweden had a few female speakers and I noticed quite a few female engineers there too. I made a point of talking to a few of them and they all seemed to be happy to be here and enjoying the conference and the company. The impression I got was that everyone felt this was a good and safe environment.

This increased participation of minority groups in tech is a great thing and overall metrics in the Python community show that there's been a significant increase in the participation of women at PyCons. It's more in the lines of 30/70 than 50/50 but already much better than the ratios reported just 5 years ago.

A consequnece of running a PyCon in Scandinavia is that your attendees are very likely to be predominantly white. Not just because of that being a thing in tech but because an overwhelming share of the population here is just that, white, vitamin-D defficient and likely blond. It would be nice to see a change in the demographic of the particiapnts there too and hopefully as the conference grows and more people attend that will start to balance out too.

== Conclusion
This PyCon was awesome. It was my first PyCon so I can't compare it to other PyCons but as far as other tech events go this was pretty excellent.

The volunteers were great, the atmosphere was fun, energetic, people were excited to learn and above all it was all very relaxed, laid back, friendly and inclusive.

I got to meet a bunch of interesting people and make a few new friends too. I'm very much looking forward to see them again at the next Python event here in Stockholm.


