= (In)visibility
:hp-tags: gay, lgbtq, tech, technology
:published-at: 2015-03-19

After my post on https://daenney.github.io/2015/03/16/LGBTQ-in-tech.html[LGBTQ in tech] a lot of people reached out to me, thanking me for the post, with a lot of kind words and some even with a resounding "yes that's me too". It's been heartwarming to see the support this story gathered and how the Puppet community, which is the one I interact with the most, reacted to it.

Interestingly though some have raised the point that LGBTQ are not a minority in tech. Obviously, I beg to differ. There are a few different things to consider. For starters there's simply the numbers, the amount of LGBTQ people in the world. For the sake of keeping this simple lets assume that whatever percentage we come up with can be transposed on the tech community. Then there's the difference between LGBTQ participants to a tech conference versus speakers.

I've taken to http://en.wikipedia.org/wiki/Demographics_of_sexual_orientation[Wikipedia] for some numbers. Studying the LGBTQ demographic is incredibly difficult because it is not something we can reliably measure. If we look at the numbers there we see things fluctuating between 3-15%. I'm going to pick 12% as a ballpark figure.

To put that percentage into perspective I'm going to draw on https://www.apple.com/diversity/[Apple], http://newsroom.fb.com/news/2014/06/building-a-more-diverse-facebook/[Facebook], http://www.microsoft.com/en-us/diversity/inside-microsoft/default.aspx#fbid=36pvRh_PbrT[Microsoft] and http://www.google.com/diversity/at-google.html#tab=tech[Google]'s diversity report numbers, solely for the tech part of their organisations.

Lets start with Apple:

* Women: 20%
* Race and ethnicity:
** Asian: 23%
** Latino / Hispanic:: 7%
** African American / Black: 6%
** Two or more: 2%
** Other / Undeclared: 8%

Next up, Facebook:

* Women: 15%
* Race and ethnicity:
** Asian: 41%
** Latino / Hispanic:: 3%
** Two or more: 2%
** African American / Black: 1%
** Other / Undeclared: 0%

Your turn, Microsoft:

* Women: 16.6%
* Race and ethnicity:
** Asian: 35.5%
** Latino / Hispanic: 3.9%
** African American / Black: 2.2%
** Other / Undeclared: 0.8%

Our last example, Google:

* Women: 17%
* Race and ethnicity:
** Asian: 34%
** Two or more: 3%
** Latino / Hispanic:: 2%
** African American / Black: 1%
** Other / Undeclared: 1%

Looking at those numbers the LGBTQ population comes in second or third place depending on whether one wants to consider the fairly significant Asian population as a minority. Keep in mind that we chose a fairly high figure of 12% but we can go as low as 2-3% depending on geographical location and year of the survey.

There have been studies that imply that tech has a higher number of LGBTQ participants than other areas so our number could be higher. However, we don't know and until such diversity reports start including numbers on this as well we likely never will. I've reached out to the aforementioned organisations in the hopes they will include such numbers in their next report.

But the numbers aren't actually that interesting at all. What we forget to consider is the visibility of these groups, or lack thereof. When you go to a conference you can determine the amount of female participants or speakers and the same goes for other differentiators like race and ethnicity. For better or for worse it is a physical trait and is therefor easier to see.

Identifying as LGBTQ however is not something physical. You can't see it by looking at us. Our skin doesn't glow a lovely shade of rainbow when exposed to (artificial) light or sparkle like Stephanie Meyer's vampires. Look around you at a tech conference. Is the person sitting next to you gay? Has a speaker that you've listened to ever identified as LGBTQ on stage? Has that ever happened at a tech event or talk that was not specifically geared towards discussing diversity and LGBTQ in tech? Maybe I've been going to the wrong tech conferences, but it hasn't happened to me yet.

Perhaps this is because so many of us don't want to be solely identified by that one trait, gay. But I'm starting to think that if that's what it takes for LGBTQ in tech to become more visible perhaps standing on the stage and saying "oh and I identify as LGBTQ" when introducing yourself could be a first step. LGBTQ is a minority in tech. The fact that I had to make some pretty shady assumptions and do some shady "math" to even be able to come up with a numbers story goes to show how little we know about LGBTQ in tech. Except for when we chose to show our colours during events like the http://en.wikipedia.org/wiki/Pride_parade[Pride parades] we're not only a minority but in tech we're an invisible minority. I hope we can change that.