name: CI

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  test:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build site and validate
      run: |
        docker run -e "CI=true" --rm --volume="$PWD:/srv/jekyll" daenney/blog:latest -- rake test
    - name: Jekyll deprecation warnings
      continue-on-error: true
      run: |
        docker run -e "CI=true" --rm --volume="$PWD:/srv/jekyll" daenney/blog:latest -- rake doctor
